apiVersion: libvirt.m.crossplane.io/v1beta1
kind: ProviderConfigUsage
metadata:
  name: test-usage-ns
  namespace: crossplane-system
providerConfigRef:
  name: timewarp
resourceRef:
  apiVersion: libvirt.m.crossplane.io/v1beta1
  kind: Network
  name: postgres-dr-network
  uid: "test-uid-ns"