apiVersion: nourspeed.io/v1alpha1
kind: XKvm
metadata:
  name: my-centos7-vm
spec:
  name: my-centos7-vm
  storagePoolPath: "/var/lib/libvirt/images/my-environment"
  networkName: "br0"
  providerConfigRef: "libvirt-host1"
  memory: 4096
  vcpu: 4